apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: openshift-opentelemetry-operator
  labels:
    kubernetes.io/metadata.name: openshift-opentelemetry-operator
    openshift.io/cluster-monitoring: "true"
