apiVersion: batch/v1
kind: Job
metadata:
  name: create-tempo-bucket
  namespace: minio
spec:
  backoffLimit: 3

  template:
    metadata:
      labels:
        app: create-tempo-bucket
    spec:
      restartPolicy: Never

      containers:
        - name: mc
          image: quay.io/minio/mc:latest

          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-root-credentials
                  key: MINIO_ROOT_USER

            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-root-credentials
                  key: MINIO_ROOT_PASSWORD

          command:
            - /bin/sh
            - -ec
            - |
              echo "Configurando conexão com MinIO..."

              mc alias set lab \
                http://minio.minio.svc.cluster.local:9000 \
                "${MINIO_ROOT_USER}" \
                "${MINIO_ROOT_PASSWORD}"

              echo "Criando bucket tempo..."

              mc mb \
                --ignore-existing \
                lab/tempo

              echo "Buckets existentes:"
              mc ls lab